FROM node:22.12.0 as build

# Set Working directory
WORKDIR dependancies/

# Copy dependancy files
COPY package*.json /dependancies/

# Install Dependancies
RUN npm install

# Stage 2
FROM node:22.12.0-slim

# Set working directory
WORKDIR server/

# Copy the dependancy files from build
COPY --from=build /dependancies/node_modules/ /server/node_modules/

# Copy rest of the project files
COPY . .

# Run the server
ENTRYPOINT ["node","server.js"]
