FROM node:22.12.0

# Setup app directory
WORKDIR server/

# Copy dependancy files
COPY package.json /server/
COPY package-lock.json /server/

# Run the build commands
RUN npm install

# Copy the rest of the files
COPY . .

# Run the node server
ENTRYPOINT ["node","server.js"]