FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY ../package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY ../ .

# Build the app
RUN npm run build

# Install serve to run the built app
RUN npm install -g serve

# Expose port 3000
EXPOSE 8080

# Start the app
CMD ["serve", "-s", "dist", "-l", "8080"] 